# Generated by Django 4.0.3 on 2022-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NbaNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', max_length=1000, unique=True)),
                ('title', models.CharField(default='', max_length=1000)),
                ('imgsrc', models.URLField(default='', max_length=1000)),
                ('creator', models.CharField(default='', max_length=100)),
                ('post_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
